name: "Translation Linter"
description: "Lints translation for potentially harmful content"
inputs:
  translation-dir:
    description: "Directory with translations"
    required: true
  file-mask:
    description: "Regex match for files containing translations"
    required: true
    default: "app_(.*)\\.arb"
  files:
    description: "List of files to check"
    required: true
    default: ""
  check-profanity:
    description: "Enable/disable profanity checking, enabled by default"
    required: false
    default: true
  check-similarity:
    description: "Enable/disable similarity checking, enabled by default"
    required: false
    default: true
  template:
    description: "Path to template file containing original, untranslated strings"
    required: false
  prof-notice-level:
    description: "Threshold to show notice-level profanity alerts (0-1)"
    required: false
  prof-warning-level:
    description: "Threshold to show warning-level profanity alerts (0-1)"
    required: false
  prof-error-level:
    description: "Threshold to show error-level profanity alerts (0-1)"
    required: false
  sim-notice-level:
    description: "Threshold to show notice-level similarity alerts (0-1)"
    required: false
  sim-warning-level:
    description: "Threshold to show warning-level similarity alerts (0-1)"
    required: false
  sim-error-level:
    description: "Threshold to show error-level similarity alerts (0-1)"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.check-profanity == 'false' && '--no-check-profanity' || '-' }}
    - ${{ inputs.check-similarity == 'false' && '--no-check-similarity' || '-' }}
    - "--source"
    - ${{ inputs.translation-dir }}
    - "--mask"
    - ${{ inputs.file-mask }}
    - "--files"
    - ${{ inputs.files }}
    - "--template"
    - ${{ inputs.template }}
    - "--prof-notice-level"
    - ${{ inputs.prof-notice-level }}
    - "--prof-warning-level"
    - ${{ inputs.prof-warning-level }}
    - "--prof-error-level"
    - ${{ inputs.prof-error-level }}
    - "--sim-notice-level"
    - ${{ inputs.sim-notice-level }}
    - "--sim-warning-level"
    - ${{ inputs.sim-warning-level }}
    - "--sim-error-level"
    - ${{ inputs.sim-error-level }}
