name: "Translation Linter"
description: "Lints translation for potentially harmful content"
inputs:
  translation-dir:
    description: "Directory with translations"
    required: true
  file-mask:
    description: "Regex match for files containing translations"
    required: true
    default: "app_(.*)\\.arb"
  files:
    description: "List of files to check"
    required: true
    default: ""
  notice-level:
    description: "Threshold to show notice-level alerts (0-1)"
    required: false
  warning-level:
    description: "Threshold to show warning-level alerts (0-1)"
    required: false
  error-level:
    description: "Threshold to show error-level alerts (0-1)"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--source"
    - ${{ inputs.translation-dir }}
    - "--mask"
    - ${{ inputs.file-mask }}
    - "--files"
    - ${{ inputs.files }}
    - "--notice-level"
    - ${{ inputs.notice-level }}
    - "--warning-level"
    - ${{ inputs.warning-level }}
    - "--error-level"
    - ${{ inputs.error-level }}
