name: "Translation Linter"
description: "Lints translation for potentially harmful content"
inputs:
  translation-dir:
    description: "Directory with translations"
    required: true
  file-mask:
    description: "Regex match for files containing translations"
    required: true
    default: "app_(.*)\\.arb"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--source"
    - ${{ inputs.translation-dir }}
    - "--mask"
    - ${{ inputs.file-mask }}
