name: example-action
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  # Example using this action on a directory of translations
  # Note that EN translations are effectively ignored (they are the source)
  # ES translations in this example should be acceptable and accurate
  # FR translations in this example should contain some unacceptable words
  translation-lint-action-dir-arb:
    name: translations-dir-arb
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: TranslationLint
        uses: ./ # when actually using this action, replace with ashuntu/translation-linter
        with:
          translation-dir: "example-translations"
          file-mask: "example_(.*)\\.arb"

  # Same as above, but for .po files
  translation-lint-action-dir-po:
    name: translations-dir-po
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: TranslationLint
        uses: ./ # when actually using this action, replace with ashuntu/translation-linter
        with:
          translation-dir: "example-translations"
          file-mask: "example_(.*)\\.po"

  # Same as arb, but with similarity checking enabled with `template`
  translation-lint-action-dir-arb-sim:
    name: translations-dir-arb-sim
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: TranslationLint
        uses: ./ # when actually using this action, replace with ashuntu/translation-linter
        with:
          translation-dir: "example-translations"
          file-mask: "example_(.*)\\.arb"
          template: "example-translations/example_en.arb"

  # Example for only checking changed translations files
  translation-lint-action-changed:
    name: translation-diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          separator: "," # REQUIRED
      - name: TranslationLint
        uses: ./
        with:
          file-mask: "example_(.*)\\.arb"
          files: ${{ steps.changed-files.outputs.all_changed_files }}

  # Same as arb, but with similarity checking enabled with `template`
  translation-lint-action-no-check:
    name: translations-no-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: TranslationLint
        uses: ./ # when actually using this action, replace with ashuntu/translation-linter
        with:
          translation-dir: "example-translations"
          file-mask: "example_(.*)\\.arb"
          template: "example-translations/example_en.arb"
          check-profanity: false
          check-similarity: false
